### ISSUE TITLE
say_team overflow

### ISSUE THREAD

**Issue by wizq3** [ec-/baseq3a#15]
if a player's name is maximum length (32) and they use say_team command at a location on map where target_location is >= 20 chars it will crash the game with "Com_Sprintf: Overflow of 64 (or more) in 64"

this happens in various locations on various maps but one example go to quad in center of q3ctf3 and use say_team (Middle Battlegrounds). it doesn't matter the message length, it crashes because the name[64] buffer used it too small to hold the name and location plus other formatting in string.

the solution is to just increase "name" buffer size in G_Say (g_cmds.c)

**Comment by ec-** [comment]
Please check now

**Comment by wizq3** [comment]
Yes it works now.
