### ISSUE TITLE
g_rotation isn't working

### ISSUE THREAD

**Issue by ostrich** [ec-/baseq3a#29]
I have `rotation.txt` in `.q3a/baseq3a/rotation.txt` which has:
```
$fraglimit = 10;
$timelimit = 60;
$g_gameType = 0;
q3dm6
q3dm7
q3dm13
q3dm17 /* { $timelimit = 7; $fraglimit = 50; } */
q3tourney2
```
here's my command line
`/opt/quake3/quake3e.ded.aarch64 +set fs_game baseq3a +exec server.cfg +map q3dm7`

`g_rotation` is set to `rotation.txt`.

I'm on aarch64 archlinuxarm. I compiled `baseq3a` from the `linux` dir.

Maps aren't cycling.

I also have tried `+map q3tourney2` -- it still doesn't cycle after `callvote nextmap`

Everything else works.

**Comment by ec-** [comment]
Show `gamedate` from server log, I suspect that you're using binary libraries instead of QVMs

**Comment by ostrich** [comment]
Yeah, I guess so.
`gamedate: Sep 30 2002`

I just copied everything from `baseq3a/build/linux/build/release-linux-aarch64/baseq3a` into` ~/.q3a/baseq3a`. Would I have to build `linux-qvm`? And is it possible to build `linux-qvm` on aarch64? It looks like the build tools are x86-64 only.

**Comment by ec-** [comment]
You might need to compile https://github.com/ec-/q3lcc and https://github.com/ec-/q3asm for your platform and replace existing binaries in `tools` directory

**Comment by ostrich** [comment]
Looks like it's working! Thanks!

`gamedate: Jan 24 2024`
